[package]
name = "fs_watch"
version = "0.1.0"
authors = ["Peter Lenkefi <lenkefi.peti@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_temp = { path = "../fs_temp" }
fs_path = { path = "../fs_path" }
